In [35]:
import pandas

In [40]:
Data = pandas.read_csv("data.csv", sep=",")

In [227]:
Data

,infected with covid,Dry Cough,High Fever,Sore Throat,Difficulty in breathing
0,No,0.25,0.50,0.50,0
1,Yes,0.75,0.75,1.00,0
2,No,0.50,0.50,0.25,0
3,No,0.50,0.50,0.75,0
4,No,0.25,0.25,0.50,0
5,No,0.50,0.25,1.00,0
6,Yes,0.75,1.00,1.00,0
7,Yes,1.00,1.00,0.25,0
8,Yes,0.25,1.00,0.25,1
9,Yes,0.75,0.75,1.00,1
10,No,0.25,0.50,0.25,0
11,No,0.50,0.50,0.75,0
12,No,0.50,0.25,1.00,0
13,Yes,0.75,1.00,0.25,1
14,No,0.50,0.50,0.25,0
15,No,0.50,0.25,0.50,0
16,Yes,0.25,1.00,0.75,0
17,Yes,1.00,1.00,0.25,0
18,Yes,0.25,0.75,0.25,0
19,Yes,0.50,1.00,0.75,1
20,No,0.25,0.50,1.00,0
21,Yes,1.00,0.75,0.25,0
22,Yes,0.75,0.25,0.25,1
23,No,0.25,0.25,0.50,0
24,No,1.00,0.25,0.25,0
25,Yes,0.25,0.75,0.75,1
26,No,0.50,0.50,0.25,0
27,Yes,0.75,0.75,0.75,0
28,No,0.75,0.25,0.25,0
29,Yes,1.00,0.25,1.00,0
30,Yes,0.25,1.00,1.00,0
31,No,0.50,0.50,0.25,0
32,No,0.75,0.50,0.50,0
33,No,0.75,0.25,1.00,0
34,Yes,1.00,1.00,1.00,0
35,No,0.75,0.25,0.25,0
36,Yes,1.00,0.75,0.25,0
37,Yes,0.75,0.50,0.25,1
38,No,0.50,0.25,0.50,0
39,Yes,0.75,1.00,0.75,0
40,No,0.25,0.50,0.25,0
41,Yes,1.00,0.25,1.00,0
42,Yes,1.00,0.25,0.75,0
43,No,0.25,0.75,0.25,0
44,Yes,1.00,1.00,1.00,1
45,No,0.25,0.50,1.00,0
46,No,0.50,0.25,1.00,0
47,Yes,1.00,0.25,1.00,1

In [48]:
Data_Yes = Data[Data[Data.columns[0]] == "Yes"]

In [49]:
Data_Yes

,infected with covid,Dry Cough,High Fever,Sore Throat,Difficulty in breathing
1,Yes,0.75,0.75,1.00,0
6,Yes,0.75,1.00,1.00,0
7,Yes,1.00,1.00,0.25,0
8,Yes,0.25,1.00,0.25,1
9,Yes,0.75,0.75,1.00,1
13,Yes,0.75,1.00,0.25,1
16,Yes,0.25,1.00,0.75,0
17,Yes,1.00,1.00,0.25,0
18,Yes,0.25,0.75,0.25,0
19,Yes,0.50,1.00,0.75,1
21,Yes,1.00,0.75,0.25,0
22,Yes,0.75,0.25,0.25,1
25,Yes,0.25,0.75,0.75,1
27,Yes,0.75,0.75,0.75,0
29,Yes,1.00,0.25,1.00,0
30,Yes,0.25,1.00,1.00,0
34,Yes,1.00,1.00,1.00,0
36,Yes,1.00,0.75,0.25,0
37,Yes,0.75,0.50,0.25,1
39,Yes,0.75,1.00,0.75,0
41,Yes,1.00,0.25,1.00,0
42,Yes,1.00,0.25,0.75,0
44,Yes,1.00,1.00,1.00,1
47,Yes,1.00,0.25,1.00,1

In [50]:
Data_No = Data[Data[Data.columns[0]] == "No"]

In [51]:
Data_No

,infected with covid,Dry Cough,High Fever,Sore Throat,Difficulty in breathing
0,No,0.25,0.50,0.50,0
2,No,0.50,0.50,0.25,0
3,No,0.50,0.50,0.75,0
4,No,0.25,0.25,0.50,0
5,No,0.50,0.25,1.00,0
10,No,0.25,0.50,0.25,0
11,No,0.50,0.50,0.75,0
12,No,0.50,0.25,1.00,0
14,No,0.50,0.50,0.25,0
15,No,0.50,0.25,0.50,0
20,No,0.25,0.50,1.00,0
23,No,0.25,0.25,0.50,0
24,No,1.00,0.25,0.25,0
26,No,0.50,0.50,0.25,0
28,No,0.75,0.25,0.25,0
31,No,0.50,0.50,0.25,0
32,No,0.75,0.50,0.50,0
33,No,0.75,0.25,1.00,0
35,No,0.75,0.25,0.25,0
38,No,0.50,0.25,0.50,0
40,No,0.25,0.50,0.25,0
43,No,0.25,0.75,0.25,0
45,No,0.25,0.50,1.00,0
46,No,0.50,0.25,1.00,0

In [261]:
symptoms  = {'Dry Cough': 0.25, 'High Fever': 0.50, 'Sore Throat':0.75, 'Difficulty in breathing': 1}

In [262]:
counts_yes = {}
counts_no = {}

In [263]:
for key, data in symptoms.items():
    count = list(Data_Yes[key]).count(data)
    counts_yes[key] = count

    count = list(Data_No[key]).count(data)
    counts_no[key] = count

In [264]:
counts_yes

{'Dry Cough': 5,
 'High Fever': 1,
 'Sore Throat': 6,
 'Difficulty in breathing': 9}

In [265]:
counts_no

{'Dry Cough': 8,
 'High Fever': 12,
 'Sore Throat': 2,
 'Difficulty in breathing': 0}

In [266]:
probability_yes =  []
probability_no =  []

In [267]:
a = list(Data[Data.columns[0]]).count("Yes")
b = len(list(Data[Data.columns[0]]))
p_c = a/b
p_c

0.5

In [268]:
probability_yes.append(p_c)
for key, data in counts_yes.items():
    probability_yes.append(data/a)
probability_yes

[0.5, 0.20833333333333334, 0.041666666666666664, 0.25, 0.375]

In [269]:
a = list(Data[Data.columns[0]]).count("No")
b = len(list(Data[Data.columns[0]]))
p_c = a/b
p_c

0.5

In [270]:
probability_no.append(p_c)
for key, data in counts_no.items():
    probability_no.append(data/a)
probability_no

[0.5, 0.3333333333333333, 0.5, 0.08333333333333333, 0.0]

In [271]:
muly = 1.0
for i in probability_yes:
    muly = muly*i
muly

0.0004069010416666667

In [272]:
muln = 1.0
for i in probability_no:
    muln = muln*i
muln

0.0

In [273]:
muly > muln

True